### ISSUE TITLE
UPDATE status when user has been assigned

### ISSUE THREAD

**Issue by bunnybunbun37204** [CUSW-chula/cusw-backend#15]
![image](https://github.com/user-attachments/assets/ac769567-a5db-4373-bab4-f94d17fa4588)

- [ ] อัพเดทสถานะเวลา user โดน assign จาก unassign -> assign
- [ ] อัพเดทสถานะ ถ้าไม่มี user คนไหนโดน assign จาก X -> unassigned

@ThanapatDonlachanon

**Comment by bunnybunbun37204** [comment]
มี business logic ของ การ api ด้วย เช่นลูก done หมด พ่อต้อง done หรือว่า พ่อ in recheck ลูกก็ต้องนู่นนี่ยังไง รายละเอียด @JirayuNam มาช่วยตอบหน่อย

**Comment by JirayuNam** [comment]
### Update Status Business Logic
---
unassigned to assign: bind with user,
assign -> in review -> done: bind with task
